/**
 * generated by Xtext 2.12.0
 */
package fr.imta.renaud.ssinigaglia.webDsl.impl;

import fr.imta.renaud.ssinigaglia.webDsl.CountAction;
import fr.imta.renaud.ssinigaglia.webDsl.HtmlElement;
import fr.imta.renaud.ssinigaglia.webDsl.TypeSelection;
import fr.imta.renaud.ssinigaglia.webDsl.WebDslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Count Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.imta.renaud.ssinigaglia.webDsl.impl.CountActionImpl#getHtmlElement <em>Html Element</em>}</li>
 *   <li>{@link fr.imta.renaud.ssinigaglia.webDsl.impl.CountActionImpl#getTypeSelection <em>Type Selection</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CountActionImpl extends MinimalEObjectImpl.Container implements CountAction
{
  /**
   * The default value of the '{@link #getHtmlElement() <em>Html Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHtmlElement()
   * @generated
   * @ordered
   */
  protected static final HtmlElement HTML_ELEMENT_EDEFAULT = HtmlElement.LINK;

  /**
   * The cached value of the '{@link #getHtmlElement() <em>Html Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHtmlElement()
   * @generated
   * @ordered
   */
  protected HtmlElement htmlElement = HTML_ELEMENT_EDEFAULT;

  /**
   * The cached value of the '{@link #getTypeSelection() <em>Type Selection</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeSelection()
   * @generated
   * @ordered
   */
  protected TypeSelection typeSelection;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CountActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WebDslPackage.Literals.COUNT_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HtmlElement getHtmlElement()
  {
    return htmlElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHtmlElement(HtmlElement newHtmlElement)
  {
    HtmlElement oldHtmlElement = htmlElement;
    htmlElement = newHtmlElement == null ? HTML_ELEMENT_EDEFAULT : newHtmlElement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WebDslPackage.COUNT_ACTION__HTML_ELEMENT, oldHtmlElement, htmlElement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypeSelection getTypeSelection()
  {
    return typeSelection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeSelection(TypeSelection newTypeSelection, NotificationChain msgs)
  {
    TypeSelection oldTypeSelection = typeSelection;
    typeSelection = newTypeSelection;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WebDslPackage.COUNT_ACTION__TYPE_SELECTION, oldTypeSelection, newTypeSelection);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypeSelection(TypeSelection newTypeSelection)
  {
    if (newTypeSelection != typeSelection)
    {
      NotificationChain msgs = null;
      if (typeSelection != null)
        msgs = ((InternalEObject)typeSelection).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WebDslPackage.COUNT_ACTION__TYPE_SELECTION, null, msgs);
      if (newTypeSelection != null)
        msgs = ((InternalEObject)newTypeSelection).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WebDslPackage.COUNT_ACTION__TYPE_SELECTION, null, msgs);
      msgs = basicSetTypeSelection(newTypeSelection, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WebDslPackage.COUNT_ACTION__TYPE_SELECTION, newTypeSelection, newTypeSelection));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WebDslPackage.COUNT_ACTION__TYPE_SELECTION:
        return basicSetTypeSelection(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WebDslPackage.COUNT_ACTION__HTML_ELEMENT:
        return getHtmlElement();
      case WebDslPackage.COUNT_ACTION__TYPE_SELECTION:
        return getTypeSelection();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WebDslPackage.COUNT_ACTION__HTML_ELEMENT:
        setHtmlElement((HtmlElement)newValue);
        return;
      case WebDslPackage.COUNT_ACTION__TYPE_SELECTION:
        setTypeSelection((TypeSelection)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WebDslPackage.COUNT_ACTION__HTML_ELEMENT:
        setHtmlElement(HTML_ELEMENT_EDEFAULT);
        return;
      case WebDslPackage.COUNT_ACTION__TYPE_SELECTION:
        setTypeSelection((TypeSelection)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WebDslPackage.COUNT_ACTION__HTML_ELEMENT:
        return htmlElement != HTML_ELEMENT_EDEFAULT;
      case WebDslPackage.COUNT_ACTION__TYPE_SELECTION:
        return typeSelection != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (htmlElement: ");
    result.append(htmlElement);
    result.append(')');
    return result.toString();
  }

} //CountActionImpl
