/**
 * generated by Xtext 2.12.0
 */
package fr.imta.renaud.ssinigaglia.webDsl.impl;

import fr.imta.renaud.ssinigaglia.webDsl.GeneralAction;
import fr.imta.renaud.ssinigaglia.webDsl.Selection;
import fr.imta.renaud.ssinigaglia.webDsl.SetAction;
import fr.imta.renaud.ssinigaglia.webDsl.StoreAction;
import fr.imta.renaud.ssinigaglia.webDsl.WebDslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>General Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.imta.renaud.ssinigaglia.webDsl.impl.GeneralActionImpl#getSetAction <em>Set Action</em>}</li>
 *   <li>{@link fr.imta.renaud.ssinigaglia.webDsl.impl.GeneralActionImpl#getStoreAction <em>Store Action</em>}</li>
 *   <li>{@link fr.imta.renaud.ssinigaglia.webDsl.impl.GeneralActionImpl#getSelection <em>Selection</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GeneralActionImpl extends MinimalEObjectImpl.Container implements GeneralAction
{
  /**
   * The cached value of the '{@link #getSetAction() <em>Set Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSetAction()
   * @generated
   * @ordered
   */
  protected SetAction setAction;

  /**
   * The cached value of the '{@link #getStoreAction() <em>Store Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStoreAction()
   * @generated
   * @ordered
   */
  protected StoreAction storeAction;

  /**
   * The cached value of the '{@link #getSelection() <em>Selection</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSelection()
   * @generated
   * @ordered
   */
  protected Selection selection;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GeneralActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WebDslPackage.Literals.GENERAL_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SetAction getSetAction()
  {
    return setAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSetAction(SetAction newSetAction, NotificationChain msgs)
  {
    SetAction oldSetAction = setAction;
    setAction = newSetAction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WebDslPackage.GENERAL_ACTION__SET_ACTION, oldSetAction, newSetAction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSetAction(SetAction newSetAction)
  {
    if (newSetAction != setAction)
    {
      NotificationChain msgs = null;
      if (setAction != null)
        msgs = ((InternalEObject)setAction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WebDslPackage.GENERAL_ACTION__SET_ACTION, null, msgs);
      if (newSetAction != null)
        msgs = ((InternalEObject)newSetAction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WebDslPackage.GENERAL_ACTION__SET_ACTION, null, msgs);
      msgs = basicSetSetAction(newSetAction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WebDslPackage.GENERAL_ACTION__SET_ACTION, newSetAction, newSetAction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StoreAction getStoreAction()
  {
    return storeAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStoreAction(StoreAction newStoreAction, NotificationChain msgs)
  {
    StoreAction oldStoreAction = storeAction;
    storeAction = newStoreAction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WebDslPackage.GENERAL_ACTION__STORE_ACTION, oldStoreAction, newStoreAction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStoreAction(StoreAction newStoreAction)
  {
    if (newStoreAction != storeAction)
    {
      NotificationChain msgs = null;
      if (storeAction != null)
        msgs = ((InternalEObject)storeAction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WebDslPackage.GENERAL_ACTION__STORE_ACTION, null, msgs);
      if (newStoreAction != null)
        msgs = ((InternalEObject)newStoreAction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WebDslPackage.GENERAL_ACTION__STORE_ACTION, null, msgs);
      msgs = basicSetStoreAction(newStoreAction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WebDslPackage.GENERAL_ACTION__STORE_ACTION, newStoreAction, newStoreAction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Selection getSelection()
  {
    return selection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSelection(Selection newSelection, NotificationChain msgs)
  {
    Selection oldSelection = selection;
    selection = newSelection;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WebDslPackage.GENERAL_ACTION__SELECTION, oldSelection, newSelection);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSelection(Selection newSelection)
  {
    if (newSelection != selection)
    {
      NotificationChain msgs = null;
      if (selection != null)
        msgs = ((InternalEObject)selection).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WebDslPackage.GENERAL_ACTION__SELECTION, null, msgs);
      if (newSelection != null)
        msgs = ((InternalEObject)newSelection).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WebDslPackage.GENERAL_ACTION__SELECTION, null, msgs);
      msgs = basicSetSelection(newSelection, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WebDslPackage.GENERAL_ACTION__SELECTION, newSelection, newSelection));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WebDslPackage.GENERAL_ACTION__SET_ACTION:
        return basicSetSetAction(null, msgs);
      case WebDslPackage.GENERAL_ACTION__STORE_ACTION:
        return basicSetStoreAction(null, msgs);
      case WebDslPackage.GENERAL_ACTION__SELECTION:
        return basicSetSelection(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WebDslPackage.GENERAL_ACTION__SET_ACTION:
        return getSetAction();
      case WebDslPackage.GENERAL_ACTION__STORE_ACTION:
        return getStoreAction();
      case WebDslPackage.GENERAL_ACTION__SELECTION:
        return getSelection();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WebDslPackage.GENERAL_ACTION__SET_ACTION:
        setSetAction((SetAction)newValue);
        return;
      case WebDslPackage.GENERAL_ACTION__STORE_ACTION:
        setStoreAction((StoreAction)newValue);
        return;
      case WebDslPackage.GENERAL_ACTION__SELECTION:
        setSelection((Selection)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WebDslPackage.GENERAL_ACTION__SET_ACTION:
        setSetAction((SetAction)null);
        return;
      case WebDslPackage.GENERAL_ACTION__STORE_ACTION:
        setStoreAction((StoreAction)null);
        return;
      case WebDslPackage.GENERAL_ACTION__SELECTION:
        setSelection((Selection)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WebDslPackage.GENERAL_ACTION__SET_ACTION:
        return setAction != null;
      case WebDslPackage.GENERAL_ACTION__STORE_ACTION:
        return storeAction != null;
      case WebDslPackage.GENERAL_ACTION__SELECTION:
        return selection != null;
    }
    return super.eIsSet(featureID);
  }

} //GeneralActionImpl
