/**
 * generated by Xtext 2.12.0
 */
package fr.imta.renaud.ssinigaglia.webDsl.impl;

import fr.imta.renaud.ssinigaglia.webDsl.Assert;
import fr.imta.renaud.ssinigaglia.webDsl.PageSelection;
import fr.imta.renaud.ssinigaglia.webDsl.StoreAction;
import fr.imta.renaud.ssinigaglia.webDsl.WebDslPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Page Selection</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.imta.renaud.ssinigaglia.webDsl.impl.PageSelectionImpl#getStoreActions <em>Store Actions</em>}</li>
 *   <li>{@link fr.imta.renaud.ssinigaglia.webDsl.impl.PageSelectionImpl#getAssertions <em>Assertions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PageSelectionImpl extends SelectionImpl implements PageSelection
{
  /**
   * The cached value of the '{@link #getStoreActions() <em>Store Actions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStoreActions()
   * @generated
   * @ordered
   */
  protected EList<StoreAction> storeActions;

  /**
   * The cached value of the '{@link #getAssertions() <em>Assertions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAssertions()
   * @generated
   * @ordered
   */
  protected EList<Assert> assertions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PageSelectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WebDslPackage.Literals.PAGE_SELECTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<StoreAction> getStoreActions()
  {
    if (storeActions == null)
    {
      storeActions = new EObjectContainmentEList<StoreAction>(StoreAction.class, this, WebDslPackage.PAGE_SELECTION__STORE_ACTIONS);
    }
    return storeActions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Assert> getAssertions()
  {
    if (assertions == null)
    {
      assertions = new EObjectContainmentEList<Assert>(Assert.class, this, WebDslPackage.PAGE_SELECTION__ASSERTIONS);
    }
    return assertions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WebDslPackage.PAGE_SELECTION__STORE_ACTIONS:
        return ((InternalEList<?>)getStoreActions()).basicRemove(otherEnd, msgs);
      case WebDslPackage.PAGE_SELECTION__ASSERTIONS:
        return ((InternalEList<?>)getAssertions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WebDslPackage.PAGE_SELECTION__STORE_ACTIONS:
        return getStoreActions();
      case WebDslPackage.PAGE_SELECTION__ASSERTIONS:
        return getAssertions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WebDslPackage.PAGE_SELECTION__STORE_ACTIONS:
        getStoreActions().clear();
        getStoreActions().addAll((Collection<? extends StoreAction>)newValue);
        return;
      case WebDslPackage.PAGE_SELECTION__ASSERTIONS:
        getAssertions().clear();
        getAssertions().addAll((Collection<? extends Assert>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WebDslPackage.PAGE_SELECTION__STORE_ACTIONS:
        getStoreActions().clear();
        return;
      case WebDslPackage.PAGE_SELECTION__ASSERTIONS:
        getAssertions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WebDslPackage.PAGE_SELECTION__STORE_ACTIONS:
        return storeActions != null && !storeActions.isEmpty();
      case WebDslPackage.PAGE_SELECTION__ASSERTIONS:
        return assertions != null && !assertions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //PageSelectionImpl
