/*
 * generated by Xtext 2.12.0
 */
package fr.imta.renaud.ssinigaglia.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WebDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/imta/renaud/ssinigaglia/parser/antlr/internal/InternalWebDsl.tokens");
	}
}
