/**
 * generated by Xtext 2.12.0
 */
package org.imt.sinigaglia.renaud.testDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.imt.sinigaglia.renaud.testDsl.CheckboxSelection;
import org.imt.sinigaglia.renaud.testDsl.GeneralAction;
import org.imt.sinigaglia.renaud.testDsl.TestDslPackage;
import org.imt.sinigaglia.renaud.testDsl.TypeSelection;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Checkbox Selection</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.imt.sinigaglia.renaud.testDsl.impl.CheckboxSelectionImpl#getTypeSelection <em>Type Selection</em>}</li>
 *   <li>{@link org.imt.sinigaglia.renaud.testDsl.impl.CheckboxSelectionImpl#getGeneralAction <em>General Action</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CheckboxSelectionImpl extends MinimalEObjectImpl.Container implements CheckboxSelection
{
  /**
   * The cached value of the '{@link #getTypeSelection() <em>Type Selection</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeSelection()
   * @generated
   * @ordered
   */
  protected TypeSelection typeSelection;

  /**
   * The cached value of the '{@link #getGeneralAction() <em>General Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGeneralAction()
   * @generated
   * @ordered
   */
  protected GeneralAction generalAction;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CheckboxSelectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TestDslPackage.Literals.CHECKBOX_SELECTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypeSelection getTypeSelection()
  {
    return typeSelection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeSelection(TypeSelection newTypeSelection, NotificationChain msgs)
  {
    TypeSelection oldTypeSelection = typeSelection;
    typeSelection = newTypeSelection;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TestDslPackage.CHECKBOX_SELECTION__TYPE_SELECTION, oldTypeSelection, newTypeSelection);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypeSelection(TypeSelection newTypeSelection)
  {
    if (newTypeSelection != typeSelection)
    {
      NotificationChain msgs = null;
      if (typeSelection != null)
        msgs = ((InternalEObject)typeSelection).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TestDslPackage.CHECKBOX_SELECTION__TYPE_SELECTION, null, msgs);
      if (newTypeSelection != null)
        msgs = ((InternalEObject)newTypeSelection).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TestDslPackage.CHECKBOX_SELECTION__TYPE_SELECTION, null, msgs);
      msgs = basicSetTypeSelection(newTypeSelection, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TestDslPackage.CHECKBOX_SELECTION__TYPE_SELECTION, newTypeSelection, newTypeSelection));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GeneralAction getGeneralAction()
  {
    return generalAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGeneralAction(GeneralAction newGeneralAction, NotificationChain msgs)
  {
    GeneralAction oldGeneralAction = generalAction;
    generalAction = newGeneralAction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TestDslPackage.CHECKBOX_SELECTION__GENERAL_ACTION, oldGeneralAction, newGeneralAction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGeneralAction(GeneralAction newGeneralAction)
  {
    if (newGeneralAction != generalAction)
    {
      NotificationChain msgs = null;
      if (generalAction != null)
        msgs = ((InternalEObject)generalAction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TestDslPackage.CHECKBOX_SELECTION__GENERAL_ACTION, null, msgs);
      if (newGeneralAction != null)
        msgs = ((InternalEObject)newGeneralAction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TestDslPackage.CHECKBOX_SELECTION__GENERAL_ACTION, null, msgs);
      msgs = basicSetGeneralAction(newGeneralAction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TestDslPackage.CHECKBOX_SELECTION__GENERAL_ACTION, newGeneralAction, newGeneralAction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TestDslPackage.CHECKBOX_SELECTION__TYPE_SELECTION:
        return basicSetTypeSelection(null, msgs);
      case TestDslPackage.CHECKBOX_SELECTION__GENERAL_ACTION:
        return basicSetGeneralAction(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TestDslPackage.CHECKBOX_SELECTION__TYPE_SELECTION:
        return getTypeSelection();
      case TestDslPackage.CHECKBOX_SELECTION__GENERAL_ACTION:
        return getGeneralAction();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TestDslPackage.CHECKBOX_SELECTION__TYPE_SELECTION:
        setTypeSelection((TypeSelection)newValue);
        return;
      case TestDslPackage.CHECKBOX_SELECTION__GENERAL_ACTION:
        setGeneralAction((GeneralAction)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TestDslPackage.CHECKBOX_SELECTION__TYPE_SELECTION:
        setTypeSelection((TypeSelection)null);
        return;
      case TestDslPackage.CHECKBOX_SELECTION__GENERAL_ACTION:
        setGeneralAction((GeneralAction)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TestDslPackage.CHECKBOX_SELECTION__TYPE_SELECTION:
        return typeSelection != null;
      case TestDslPackage.CHECKBOX_SELECTION__GENERAL_ACTION:
        return generalAction != null;
    }
    return super.eIsSet(featureID);
  }

} //CheckboxSelectionImpl
