/*
 * generated by Xtext 2.12.0
 */
package fr.imta.renaud.ssinigaglia.ide


/**
 * Use this class to register ide components.
 */
class WebDslIdeModule extends AbstractWebDslIdeModule {
}
