/*
 * generated by Xtext 2.12.0
 */
package fr.imta.renaud.ssinigaglia


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class WebDslRuntimeModule extends AbstractWebDslRuntimeModule {
}
