/*
 * generated by Xtext 2.12.0
 */
package fr.imta.renaud.ssinigaglia.serializer;

import com.google.inject.Inject;
import fr.imta.renaud.ssinigaglia.services.WebDslGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class WebDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected WebDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_TypeSelection_ALLKeyword_4_or_FIRSTKeyword_2_or_LASTKeyword_3_or_PARENTKeyword_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (WebDslGrammarAccess) access;
		match_TypeSelection_ALLKeyword_4_or_FIRSTKeyword_2_or_LASTKeyword_3_or_PARENTKeyword_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getTypeSelectionAccess().getALLKeyword_4()), new TokenAlias(false, false, grammarAccess.getTypeSelectionAccess().getFIRSTKeyword_2()), new TokenAlias(false, false, grammarAccess.getTypeSelectionAccess().getLASTKeyword_3()), new TokenAlias(false, false, grammarAccess.getTypeSelectionAccess().getPARENTKeyword_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getSTRINGRule())
			return getSTRINGToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal STRING	: 
	 * 			'"' ( '\\' .  | !('\\'|'"') )* '"' |
	 * 			"'" ( '\\' .  | !('\\'|"'") )* "'"
	 * 		;
	 */
	protected String getSTRINGToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\"\"";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_TypeSelection_ALLKeyword_4_or_FIRSTKeyword_2_or_LASTKeyword_3_or_PARENTKeyword_1.equals(syntax))
				emit_TypeSelection_ALLKeyword_4_or_FIRSTKeyword_2_or_LASTKeyword_3_or_PARENTKeyword_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'PARENT' | 'FIRST' | 'LAST' | 'ALL'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_TypeSelection_ALLKeyword_4_or_FIRSTKeyword_2_or_LASTKeyword_3_or_PARENTKeyword_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
