/*
 * generated by Xtext 2.12.0
 */
package fr.imta.renaud.ssinigaglia.serializer;

import com.google.inject.Inject;
import fr.imta.renaud.ssinigaglia.services.WebDslGrammarAccess;
import fr.imta.renaud.ssinigaglia.webDsl.Assert;
import fr.imta.renaud.ssinigaglia.webDsl.AssertContains;
import fr.imta.renaud.ssinigaglia.webDsl.AssertEquals;
import fr.imta.renaud.ssinigaglia.webDsl.CheckboxSelection;
import fr.imta.renaud.ssinigaglia.webDsl.ComboboxSelection;
import fr.imta.renaud.ssinigaglia.webDsl.Core;
import fr.imta.renaud.ssinigaglia.webDsl.GeneralAction;
import fr.imta.renaud.ssinigaglia.webDsl.GeneralSelection;
import fr.imta.renaud.ssinigaglia.webDsl.GoAction;
import fr.imta.renaud.ssinigaglia.webDsl.LinkButtonSelection;
import fr.imta.renaud.ssinigaglia.webDsl.PageSelection;
import fr.imta.renaud.ssinigaglia.webDsl.Program;
import fr.imta.renaud.ssinigaglia.webDsl.Selection;
import fr.imta.renaud.ssinigaglia.webDsl.SetAction;
import fr.imta.renaud.ssinigaglia.webDsl.StoreAction;
import fr.imta.renaud.ssinigaglia.webDsl.TypeSelection;
import fr.imta.renaud.ssinigaglia.webDsl.Var;
import fr.imta.renaud.ssinigaglia.webDsl.WebDslPackage;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class WebDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private WebDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == WebDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case WebDslPackage.ACTION:
				sequence_Action(context, (fr.imta.renaud.ssinigaglia.webDsl.Action) semanticObject); 
				return; 
			case WebDslPackage.ASSERT:
				sequence_Assert(context, (Assert) semanticObject); 
				return; 
			case WebDslPackage.ASSERT_CONTAINS:
				sequence_AssertContains(context, (AssertContains) semanticObject); 
				return; 
			case WebDslPackage.ASSERT_EQUALS:
				sequence_AssertEquals(context, (AssertEquals) semanticObject); 
				return; 
			case WebDslPackage.CHECKBOX_SELECTION:
				sequence_CheckboxSelection(context, (CheckboxSelection) semanticObject); 
				return; 
			case WebDslPackage.COMBOBOX_SELECTION:
				sequence_ComboboxSelection(context, (ComboboxSelection) semanticObject); 
				return; 
			case WebDslPackage.COMPARABLE:
				sequence_Comparable(context, (fr.imta.renaud.ssinigaglia.webDsl.Comparable) semanticObject); 
				return; 
			case WebDslPackage.CORE:
				sequence_Core(context, (Core) semanticObject); 
				return; 
			case WebDslPackage.GENERAL_ACTION:
				sequence_GeneralAction(context, (GeneralAction) semanticObject); 
				return; 
			case WebDslPackage.GENERAL_SELECTION:
				sequence_GeneralSelection(context, (GeneralSelection) semanticObject); 
				return; 
			case WebDslPackage.GO_ACTION:
				sequence_GoAction(context, (GoAction) semanticObject); 
				return; 
			case WebDslPackage.LINK_BUTTON_SELECTION:
				sequence_LinkButtonSelection(context, (LinkButtonSelection) semanticObject); 
				return; 
			case WebDslPackage.PAGE_SELECTION:
				sequence_PageSelection(context, (PageSelection) semanticObject); 
				return; 
			case WebDslPackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			case WebDslPackage.SELECTION:
				sequence_Selection(context, (Selection) semanticObject); 
				return; 
			case WebDslPackage.SET_ACTION:
				sequence_SetAction(context, (SetAction) semanticObject); 
				return; 
			case WebDslPackage.STORE_ACTION:
				sequence_StoreAction(context, (StoreAction) semanticObject); 
				return; 
			case WebDslPackage.TYPE_SELECTION:
				sequence_TypeSelection(context, (TypeSelection) semanticObject); 
				return; 
			case WebDslPackage.VAR:
				sequence_Var(context, (Var) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Action returns Action
	 *
	 * Constraint:
	 *     (goAction=GoAction | selection=Selection)
	 */
	protected void sequence_Action(ISerializationContext context, fr.imta.renaud.ssinigaglia.webDsl.Action semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AssertContains returns AssertContains
	 *
	 * Constraint:
	 *     (htmlElement=HtmlElement attribute=Attribute)
	 */
	protected void sequence_AssertContains(ISerializationContext context, AssertContains semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.ASSERT_CONTAINS__HTML_ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.ASSERT_CONTAINS__HTML_ELEMENT));
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.ASSERT_CONTAINS__ATTRIBUTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.ASSERT_CONTAINS__ATTRIBUTE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAssertContainsAccess().getHtmlElementHtmlElementEnumRuleCall_1_0_0_0(), semanticObject.getHtmlElement());
		feeder.accept(grammarAccess.getAssertContainsAccess().getAttributeAttributeEnumRuleCall_1_0_1_0(), semanticObject.getAttribute());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AssertEquals returns AssertEquals
	 *
	 * Constraint:
	 *     (c1=Comparable c2=Comparable)
	 */
	protected void sequence_AssertEquals(ISerializationContext context, AssertEquals semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.ASSERT_EQUALS__C1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.ASSERT_EQUALS__C1));
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.ASSERT_EQUALS__C2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.ASSERT_EQUALS__C2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAssertEqualsAccess().getC1ComparableParserRuleCall_0_0(), semanticObject.getC1());
		feeder.accept(grammarAccess.getAssertEqualsAccess().getC2ComparableParserRuleCall_2_0(), semanticObject.getC2());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Assert returns Assert
	 *
	 * Constraint:
	 *     (assertContain=AssertContains | assertEquals=AssertEquals)
	 */
	protected void sequence_Assert(ISerializationContext context, Assert semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     CheckboxSelection returns CheckboxSelection
	 *
	 * Constraint:
	 *     (typeSelection=TypeSelection generalActions+=GeneralAction*)
	 */
	protected void sequence_CheckboxSelection(ISerializationContext context, CheckboxSelection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ComboboxSelection returns ComboboxSelection
	 *
	 * Constraint:
	 *     (typeSelection=TypeSelection generalActions+=GeneralAction*)
	 */
	protected void sequence_ComboboxSelection(ISerializationContext context, ComboboxSelection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Comparable returns Comparable
	 *
	 * Constraint:
	 *     (htmlElement=HtmlElement attribute=Attribute)
	 */
	protected void sequence_Comparable(ISerializationContext context, fr.imta.renaud.ssinigaglia.webDsl.Comparable semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.COMPARABLE__HTML_ELEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.COMPARABLE__HTML_ELEMENT));
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.COMPARABLE__ATTRIBUTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.COMPARABLE__ATTRIBUTE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getComparableAccess().getHtmlElementHtmlElementEnumRuleCall_1_1_0(), semanticObject.getHtmlElement());
		feeder.accept(grammarAccess.getComparableAccess().getAttributeAttributeEnumRuleCall_1_2_0(), semanticObject.getAttribute());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Core returns Core
	 *
	 * Constraint:
	 *     (name=Browser actions+=Action*)
	 */
	protected void sequence_Core(ISerializationContext context, Core semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GeneralAction returns GeneralAction
	 *
	 * Constraint:
	 *     (setAction=SetAction | storeAction=StoreAction | selection=Selection)
	 */
	protected void sequence_GeneralAction(ISerializationContext context, GeneralAction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GeneralSelection returns GeneralSelection
	 *
	 * Constraint:
	 *     (typeSelection=TypeSelection generalActions+=GeneralAction*)
	 */
	protected void sequence_GeneralSelection(ISerializationContext context, GeneralSelection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GoAction returns GoAction
	 *
	 * Constraint:
	 *     name=STRING
	 */
	protected void sequence_GoAction(ISerializationContext context, GoAction semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.GO_ACTION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.GO_ACTION__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getGoActionAccess().getNameSTRINGTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     LinkButtonSelection returns LinkButtonSelection
	 *
	 * Constraint:
	 *     (typeSelection=TypeSelection generalActions+=GeneralAction*)
	 */
	protected void sequence_LinkButtonSelection(ISerializationContext context, LinkButtonSelection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PageSelection returns PageSelection
	 *
	 * Constraint:
	 *     (storeAction=StoreAction | assertion=Assert)+
	 */
	protected void sequence_PageSelection(ISerializationContext context, PageSelection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     core=Core
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.PROGRAM__CORE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.PROGRAM__CORE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getProgramAccess().getCoreCoreParserRuleCall_0(), semanticObject.getCore());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Selection returns Selection
	 *
	 * Constraint:
	 *     (
	 *         linkButtonSelection=LinkButtonSelection | 
	 *         generalSelection=GeneralSelection | 
	 *         checkboxSelection=CheckboxSelection | 
	 *         comboboxSelection=ComboboxSelection | 
	 *         pageSelection=PageSelection
	 *     )
	 */
	protected void sequence_Selection(ISerializationContext context, Selection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SetAction returns SetAction
	 *
	 * Constraint:
	 *     (attribute=Attribute value=STRING)
	 */
	protected void sequence_SetAction(ISerializationContext context, SetAction semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.SET_ACTION__ATTRIBUTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.SET_ACTION__ATTRIBUTE));
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.SET_ACTION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.SET_ACTION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSetActionAccess().getAttributeAttributeEnumRuleCall_1_0(), semanticObject.getAttribute());
		feeder.accept(grammarAccess.getSetActionAccess().getValueSTRINGTerminalRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     StoreAction returns StoreAction
	 *
	 * Constraint:
	 *     var=Var
	 */
	protected void sequence_StoreAction(ISerializationContext context, StoreAction semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.STORE_ACTION__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.STORE_ACTION__VAR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStoreActionAccess().getVarVarParserRuleCall_3_0(), semanticObject.getVar());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     TypeSelection returns TypeSelection
	 *
	 * Constraint:
	 *     (attribute=Attribute value=STRING)
	 */
	protected void sequence_TypeSelection(ISerializationContext context, TypeSelection semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.TYPE_SELECTION__ATTRIBUTE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.TYPE_SELECTION__ATTRIBUTE));
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.TYPE_SELECTION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.TYPE_SELECTION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTypeSelectionAccess().getAttributeAttributeEnumRuleCall_0_0_0(), semanticObject.getAttribute());
		feeder.accept(grammarAccess.getTypeSelectionAccess().getValueSTRINGTerminalRuleCall_0_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Var returns Var
	 *
	 * Constraint:
	 *     name=STRING
	 */
	protected void sequence_Var(ISerializationContext context, Var semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WebDslPackage.Literals.VAR__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WebDslPackage.Literals.VAR__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVarAccess().getNameSTRINGTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
