/**
 * generated by Xtext 2.12.0
 */
package fr.imta.renaud.ssinigaglia.webDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imta.renaud.ssinigaglia.webDsl.Program#getProcedures <em>Procedures</em>}</li>
 *   <li>{@link fr.imta.renaud.ssinigaglia.webDsl.Program#getCores <em>Cores</em>}</li>
 * </ul>
 *
 * @see fr.imta.renaud.ssinigaglia.webDsl.WebDslPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Procedures</b></em>' containment reference list.
   * The list contents are of type {@link fr.imta.renaud.ssinigaglia.webDsl.Procedure}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Procedures</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procedures</em>' containment reference list.
   * @see fr.imta.renaud.ssinigaglia.webDsl.WebDslPackage#getProgram_Procedures()
   * @model containment="true"
   * @generated
   */
  EList<Procedure> getProcedures();

  /**
   * Returns the value of the '<em><b>Cores</b></em>' containment reference list.
   * The list contents are of type {@link fr.imta.renaud.ssinigaglia.webDsl.Core}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cores</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cores</em>' containment reference list.
   * @see fr.imta.renaud.ssinigaglia.webDsl.WebDslPackage#getProgram_Cores()
   * @model containment="true"
   * @generated
   */
  EList<Core> getCores();

} // Program
